// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        pgtype.UUID
	Username  string
	Email     string
	IsActive  pgtype.Bool
	CreatedAt pgtype.Timestamptz
}

type UserPass struct {
	ID           pgtype.UUID
	PasswordHash string
	UpdatedAt    pgtype.Timestamptz
}
