// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :exec
WITH new_user AS (
    INSERT INTO users (username, email, is_active)
    VALUES ($1, $2, true)
    RETURNING id
)
INSERT INTO user_pass (id, password_hash)
SELECT id, $3
FROM new_user
`

type CreateUserParams struct {
	Username     string
	Email        string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.Username, arg.Email, arg.PasswordHash)
	return err
}

const getHash = `-- name: GetHash :one
SELECT password_hash
FROM user_pass
WHERE id = $1
`

func (q *Queries) GetHash(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getHash, id)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const getUserFromID = `-- name: GetUserFromID :one
SELECT id, username, email, is_active, created_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserFromID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserFromID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getUserFromName = `-- name: GetUserFromName :one
SELECT id, username, email, is_active, created_at
FROM users
WHERE username = $1
`

func (q *Queries) GetUserFromName(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserFromName, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const updateHash = `-- name: UpdateHash :exec
UPDATE user_pass
SET password_hash = $2
WHERE id = $1
`

type UpdateHashParams struct {
	ID           pgtype.UUID
	PasswordHash string
}

func (q *Queries) UpdateHash(ctx context.Context, arg UpdateHashParams) error {
	_, err := q.db.Exec(ctx, updateHash, arg.ID, arg.PasswordHash)
	return err
}
